name: Hola Mundo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Imprimir "Hola Mundo"
        run: echo "Hola Mundo"
