name: Deploy to Surge

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Instalar surge
        run: |
          npm install --global surge

      - name: Hacer deploy
        run: |
          surge --project ./ --domain ${env.SURGE_SUBDOMAIN} --token ${{ secrets.SURGE_API_KEY }}
